tx: throw if an error is present when attempting to send
e.g. with sendtoaddress, before:
RuntimeError: OrderedDict([('action', 'sign_transaction'), ('error', 'missing field `transaction`'), ('name', 'sign_transaction'), ('status', 'error')])

after:
Error: id_insufficient_funds